<!DOCTYPE html>
<html>
<head>
    <title>Shop Owners Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Shop Owners Records Report</h1>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Aadhar</th>
                <th>Device</th>
                <th>Work</th>
                <th>IMEI</th>
                <th>Doc</th>
                <th>Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $owner)
            <tr>
                <td>{{ $owner->id }}</td>
                <td>{{ $owner->name }}</td>
                <td>{{ $owner->mobile_number }}</td>
                <td>{{ $owner->aadhar_number }}</td>
                <td>{{ $owner->mobile_name }}</td>
                <td>{{ $owner->work }}</td>
                <td>{{ $owner->imei_number }}</td>
                <td>{{ $owner->document ? 'Yes' : 'No' }}</td>
                <td>{{ $owner->date }}</td>
                <td>{{ $owner->device_status }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Page report generated by RecordMaintain Admin Panel
    </div>
</body>
</html>
