<!DOCTYPE html>
<html>
<head>
    <title>Customers Report</title>
    <style>
        body { font-family: sans-serif; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 9px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Records Report</h1>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Mobile</th>
                <th>Aadhar</th>
                <th>Device</th>
                <th>Work</th>
                <th>IMEI</th>
                <th>Doc</th>
                <th>Invoice</th>
                <th>Date</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $customer)
            <tr>
                <td>{{ $customer->id }}</td>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->mobile_number }}</td>
                <td>{{ $customer->aadhar_number }}</td>
                <td>{{ $customer->mobile_name }}</td>
                <td>{{ $customer->work }}</td>
                <td>{{ $customer->imei_number }}</td>
                <td>{{ $customer->document ? 'Yes' : 'No' }}</td>
                <td>{{ $customer->invoice_bill }}</td>
                <td>{{ $customer->date }}</td>
                <td>{{ $customer->device_status }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Page report generated by RecordMaintain Admin Panel
    </div>
</body>
</html>
